language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      sudo: required
      env:
        - BUILD_APIDOC=true
        # Auth token to push API documentation
        - secure: "JKeXk8p65hodb12PVRST6A90swsNubc+46EbSJGSghldIxbFWLBAlwU+KLeOMO4V0veu6k4lnMa50V0UYFZmoUsS6W0aL5Ybo98SpzXHiNLOmOluoqJoF9TBsOTCCRFbWbccgJyVEtulgRcdml96naS51lq9Sw/VO/N3Z472304="
    - os: osx
      compiler: clang
      env:
        - BUILD_OSX=true
  allow_failures:
    - env: BUILD_APIDOC=true
    - env: BUILD_OSX=true
branches:
  only:
  - master
  - travis-with-osx
install:
  - >
    if [[ "${BUILD_APIDOC}" == "true" ]]; then
      # Update system
      sudo apt-get update -qq
      # Install dependencies
      sudo apt-get install -qq cmake python doxygen python2.7-dev libfreetype6-dev libglew-dev libopenal-dev libogg-dev libvorbis-dev zlib1g-dev libsdl2-dev mesa-common-dev python libpng12-dev libboost1.54-dev libboost-thread1.54-dev libboost-system1.54-dev libboost-signals1.54-dev libboost-serialization1.54-dev libboost-regex1.54-dev libboost-python1.54-dev libboost-log1.54-dev libboost-iostreams1.54-dev libboost-locale1.54-dev libboost-filesystem1.54-dev libboost-date-time1.54-dev
    fi
before_script:
  # Configure git to use the identity of FreeOrion Build Bot and
  # load credentials
  - >
    if [[ "${BUILD_APIDOC}" == "true" ]]; then
      git config --global user.email "freeorionorg@gmail.com"
      git config --global user.name "FreeOrion Build Bot"
      git config --global credential.helper "cache --timeout=300"
      echo -e "url=https://freeorion-bot:${FreeOrion_AUTH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git\n" | git credential approve
    fi
  - mkdir build
  - cd build
script:
  - cmake ..
  - >
    if [[ "${BUILD_APIDOC}" == "true" && "${TRAVIS_BRANCH}" == "master" ]]; then
      cmake --build . --target apidoc-deploy
    fi
